[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && npm install --legacy-peer-deps",
  "cd frontend && npm run build"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "python server.py"
